services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raw
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d raw"]
      interval: 2s
      timeout: 3s
      retries: 30
    
  dbt:
    platform: linux/amd64
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.2
    working_dir: /dbt/awards_dbt
    volumes:
      - ./dbt:/dbt
    environment:
      DBT_PROFILES_DIR: /dbt
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - app-logs:/app/logs
    environment:
      DB_DRIVER: postgresql+psycopg2
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: raw
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  app-logs: